services:
  - type: web
    name: deckbox-searcher
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
